# Makefile for hello.c
main: main.c func.c
#	gcc -Wall -o ruijo.out main.c func.c -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
	gcc -lm -o ruijo.out main.c func.c -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
